force-app/main/default/objects/LogInToExperienceObjectManager__mdt/LogInToExperienceObjectManager__mdt.object-meta.xml
<CustomObject>
    <description
  >The object Manager is used to set the CRUD permissions to users while leveraging the Log in to experience as user in Salesforce.</description>
    <label>Log In To Experience Object Manager</label>
    <pluralLabel>Log In To Experience Object Managers</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/Create_Access_Check__c.field-meta.xml
<CustomField>
    <fullName>Create_Access_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Create access to records while leveraging the Login to Experience as User functionality. Check to enforce security.
Only users with the create access while leveraging the Login to Experience as User functionality will be able to edit.</description>
    <label>Create Access Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/Delete_Access_Check__c.field-meta.xml
<CustomField>
    <fullName>Delete_Access_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Delete access to records while leveraging the Login to Experience as User functionality. Check to enforce security. 
Only users with the delete access while leveraging the Login to Experience as User functionality will be able to edit.</description>
    <label>Delete Access Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/Edit_Access_Check__c.field-meta.xml
<CustomField>
    <fullName>Edit_Access_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Edit access to records while leveraging the Login to Experience as User functionality. Check to enforce security. 
Only users with the edit access while leveraging the Login to Experience as User functionality will be able to edit.</description>
    <label>Edit Access Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description
  >Selected Object to manage the access while leveraging the Log in to Experience as User in Salesforce</description>
    <label>SObject</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/test classes/LogInToExperienceTrigger_Test.cls
@IsTest
public class LogInToExperienceTrigger_Test {
  @TestSetup
  static void setup() {
    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
    User u = new User(
      Alias = 'standt',
      Email = 'systemuser@uravttest.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = p.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = 'systemuser@uravttest.com'
    );

    insert u;
    List<String> psNames = new List<String>{
      'LogInToExperienceAsUser_Create',
      'LogInToExperienceAsUser_Read'
    };

    List<PermissionSet> psets = [
      SELECT Id
      FROM PermissionSet
      WHERE Name IN :psNames
    ];

    for (PermissionSet ps : psets) {
      insert new PermissionSetAssignment(
        AssigneeId = u.id,
        PermissionSetId = ps.Id
      );
    }
  }

  @IsTest
  static void testCreate() {
    User u = [
      SELECT id, Username
      FROM User
      WHERE Username = 'systemuser@uravttest.com'
      LIMIT 1
    ];
    System.runAs(u) {
      LogInToExperienceObjectManager__mdt theRecord = new LogInToExperienceObjectManager__mdt();
      theRecord.DeveloperName = 'Account MTD';
      theRecord.SObject__c = 'Account';
      theRecord.Create_Access_Check__c = true;
      theRecord.Edit_Access_Check__c = true;
      theRecord.Delete_Access_Check__c = true;

      Account a = new Account(name = 'TestAcc');
      ObjectManagerConfig_MTD.MDObjectManager testObjMdt = new ObjectManagerConfig_MTD.MDObjectManager(
        theRecord
      );
      LogInToExperienceManagementTrigger.handleObjectPermission(
        new List<SObject>{ a }
      );
      LogInToExperienceManagementTrigger.handleTriggerTransaction(
        'BEFORE_INSERT',
        true,
        true,
        true,
        testObjMdt,
        a
      );
      LogInToExperienceManagementTrigger.handleTriggerTransaction(
        'BEFORE_UPDATE',
        true,
        true,
        true,
        testObjMdt,
        a
      );
      LogInToExperienceManagementTrigger.handleTriggerTransaction(
        'BEFORE_DELETE',
        true,
        true,
        true,
        testObjMdt,
        a
      );
    }
  }
}