force-app/main/default/objects/LogInToExperienceObjectManager__mdt/LogInToExperienceObjectManager__mdt.object-meta.xml
<CustomObject>
    <description
  >The object Manager is used to set the CRUD permissions to users while leveraging the Log in to experience as user in Salesforce.</description>
    <label>Log In To Experience Object Manager</label>
    <pluralLabel>Log In To Experience Object Managers</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/Create_Access_Check__c.field-meta.xml
<CustomField>
    <fullName>Create_Access_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Create access to records while leveraging the Login to Experience as User functionality. Check to enforce security.
Only users with the create access while leveraging the Login to Experience as User functionality will be able to edit.</description>
    <label>Create Access Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/Delete_Access_Check__c.field-meta.xml
<CustomField>
    <fullName>Delete_Access_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Delete access to records while leveraging the Login to Experience as User functionality. Check to enforce security. 
Only users with the delete access while leveraging the Login to Experience as User functionality will be able to edit.</description>
    <label>Delete Access Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/Edit_Access_Check__c.field-meta.xml
<CustomField>
    <fullName>Edit_Access_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Edit access to records while leveraging the Login to Experience as User functionality. Check to enforce security. 
Only users with the edit access while leveraging the Login to Experience as User functionality will be able to edit.</description>
    <label>Edit Access Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogInToExperienceObjectManager__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description
  >Selected Object to manage the access while leveraging the Log in to Experience as User in Salesforce</description>
    <label>SObject</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ObjectManagerConfig_MTD.cls
/*******************************************************************************
Class Name      : ObjectManagerConfig_MTD
Description     : Class to manage the Object Manager custom metadata
Created By      : Sebastian Torres
Created Date    : 2022-21-01
Modification Log:
------------------------------------------------------------------------------- 
Developer                   Date                   Description
-------------------------------------------------------------------------------
Sebastian                 2022-21-01              Initial version
*******************************************************************************/
public class ObjectManagerConfig_MTD {
  public class MDObjectManager {
    public String Name;
    public String ManagedObject;
    public Boolean CreateAccess;
    public Boolean EditAccess;
    public Boolean DeleteAccess;

    public MDObjectManager(LogInToExperienceObjectManager__mdt source) {
      ManagedObject = source.SObject__c;
      CreateAccess = source.Create_Access_Check__c;
      EditAccess = source.Edit_Access_Check__c;
      DeleteAccess = source.Delete_Access_Check__c;
      Name = source.DeveloperName;
    }

    // Constructor that sets default values
    public MDObjectManager(String MDName) {
      ManagedObject = 'Account';
      CreateAccess = true;
      EditAccess = true;
      DeleteAccess = true;
      Name = MDName;
    }
  }

  //Configuration of The metadata

  @testvisible
  private static MDObjectManager cachedConfig = null;

  public static MDObjectManager getConfig(String mdName) {
    if (cachedConfig != null)
      return cachedConfig;

    List<LogInToExperienceObjectManager__mdt> settings = [
      SELECT
        DeveloperName,
        MasterLabel,
        SObject__c,
        Create_Access_Check__c,
        Edit_Access_Check__c,
        Delete_Access_Check__c
      FROM LogInToExperienceObjectManager__mdt
      WHERE SObject__c = :mdName
    ];

    if (settings.size() == 0 || Test.isRunningTest()) {
      cachedConfig = new MDObjectManager('Default');
      return cachedConfig;
    }
    return new MDObjectManager(settings[0]);
  }
}